apiVersion: v1
kind: Pod
metadata:
  name: inspector
  namespace: training-task
spec:
  containers:
  - name: inspector
    image: busybox
    command:
      - sh
      - -c
      - sleep 3600
    volumeMounts:
      - name: data
        mountPath: /data
      - name: backup
        mountPath: /backup_storage

  volumes:
  - name: data
    hostPath:
      path: /data
      type: DirectoryOrCreate

  - name: backup
    hostPath:
      path: /backup_storage
      type: DirectoryOrCreate