apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: threetier-green
  name: threetier-green
  namespace: bluegreen-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: threetier-green
  template:
    metadata:
      labels:
        app: threetier-green
    spec:
      containers:
      - name: threetier-green
        image: vaishnavi639/three-tier-newdeploy:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"  
          limits:   
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: threetier-service
  namespace: bluegreen-namespace
spec:
  selector:
    app: threetier-green
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5000
    nodePort: 30001