apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier
  namespace: recreate-namespace
spec:
  replicas: 2 
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: three-tier
  template:
    metadata:
      labels:
        app: three-tier
    spec:   
      containers:
      - name: three-tier
        image: vaishnavi639/three-tier:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
    